name       : abireport
version    : 1.0.5
release    : 3
source     :
    - https://github.com/clearlinux/abireport/releases/download/v1.0.5/abireport-1.0.5.tar.gz : a0b6fa0a5b160e3a40937e7e636729aaf55a033986f8c3abe59742d83216e162
license    : Apache-2.0
component  : system.devel
summary    : ABI Report for ELF Binaries
description: |
    Tool to create ABI reports from ELF binaries in packaging
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
