name       : abireport
version    : 1.0.2
release    : 2
source     :
    - https://github.com/clearlinux/abireport/releases/download/v1.0.2/abireport-1.0.2.tar.gz : 038026dfd87d880d9ffc56fbefc5b3044920c0493868a192bbea6d128d8be137
license    : Apache-2.0
component  : system.devel
summary    : ABI Report for ELF Binaries
description: |
    Tool to create ABI reports from ELF binaries in packaging
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
