name       : abireport
version    : 1.0.6
release    : 4
source     :
    - https://github.com/clearlinux/abireport/releases/download/v1.0.6/abireport-1.0.6.tar.gz : 60beb805335302f999c32bda62f56afd6971f27499580fece84fe4d6bb9cb653
license    : Apache-2.0
component  : system.devel
summary    : ABI Report for ELF Binaries
description: |
    Tool to create ABI reports from ELF binaries in packaging
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
