name       : abireport
version    : 1.0.7
release    : 5
source     :
    - https://github.com/clearlinux/abireport/releases/download/v1.0.7/abireport-1.0.7.tar.gz : c46c46bff3dc873cb84a66c639c38b2df14f095d95a4bb77e3b96904b8219399
license    : Apache-2.0
component  : system.devel
summary    : ABI Report for ELF Binaries
description: |
    Tool to create ABI reports from ELF binaries in packaging
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
