name       : abireport
version    : 1.0.1
release    : 1
source     :
    - https://github.com/clearlinux/abireport/releases/download/v1.0.1/abireport-1.0.1.tar.gz : cdce1fe160caf29014dd81089a0e0f21b50bcc006247f24e2694a881c301eabb
license    : Apache-2.0
component  : system.devel
summary    : ABI Report for ELF Binaries
description: |
    Tool to create ABI reports from ELF binaries in packaging
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
